server:
  port: 7001

spring:
  application:
    name: ms-core-reigstry

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka